#!/usr/bin/env sh

# git clean filter for tmsu database
# 
# Copyright © 2016 Wilson, Brandon
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


DATE=$(date '+%Y-%m-%d-%H:%M:%S')

TMSU_DIR=.tmsu
GIT_FILTER_DIR=$(dirname $0)

TMSU_DB=$(mktemp --tmpdir tmsu.db.${DATE}.XXXXXXX)

SQL_SCHEMA_TR_FILE_TAG=${GIT_FILTER_DIR}/file_tag.tr.schema.sql
SQL_SCHEMA_TR_IMPLICATION=${GIT_FILTER_DIR}/implication.tr.schema.sql

SQL_SELECT_TR_FILE_TAG=${GIT_FILTER_DIR}/file_tag.tr.sql
SQL_SELECT_TR_IMPLICATION=${GIT_FILTER_DIR}/implication.tr.sql

SQL_TR_FILE_TAG=$(mktemp --tmpdir tmsu.db.file_tag.tr.sql.${DATE}.XXXXXXX)
SQL_TR_IMPLICATION=$(mktemp --tmpdir tmsu.db.implication.tr.sql.${DATE}.XXXXXXX)


cat > ${TMSU_DB}

sqlite3 ${TMSU_DB} < ${SQL_SELECT_TR_FILE_TAG} > ${SQL_TR_FILE_TAG}
sqlite3 ${TMSU_DB} < ${SQL_SELECT_TR_IMPLICATION} > ${SQL_TR_IMPLICATION}

sqlite3 ${TMSU_DB} 'DROP TABLE file_tag'
sqlite3 ${TMSU_DB} 'DROP TABLE implication'

sqlite3 ${TMSU_DB} < ${SQL_SCHEMA_TR_FILE_TAG}
sqlite3 ${TMSU_DB} < ${SQL_SCHEMA_TR_IMPLICATION}

sqlite3 ${TMSU_DB} < ${SQL_TR_FILE_TAG}
sqlite3 ${TMSU_DB} < ${SQL_TR_IMPLICATION}

sqlite3 ${TMSU_DB} .dump
